class Organ:
    def __init__(self, strength: int = 100, vital: bool = True):
        self.strength = strength
        self.total_strength = strength
        self.vital = vital

    def remove(self):
        self.strength = self.total_strength

class Ear(Organ): ...
class Eye(Organ): ...
class Tongue(Organ): ...
class Nose(Organ): ...
class Brain(Organ): ...

class Head: ...
class Hand: ...
class Leg: ...
class Torso: ...


class Human: ...

a = Human()
print()